### ISSUE TITLE
Wrong equality check

### ISSUE THREAD

**Issue by KFBI1706** [WastefulNick/alvebetjent-bot#1]
https://github.com/WastefulNick/alvebetjent-bot/blob/5307378be7eff9f9976bc59e81e66ab1b7b0099f/bot.py#L81

Change the equality from != to == . 

Now the bot deletes all messages that contains cryptobin.co

Temporary workaround is to first send a message and edit it afterwards. 

Maybe you should check if the edited messages contains cryptobin.co aswell?

**Comment by BobTheShoplifter** [comment]
+1

**Comment by WastefulNick** [comment]
Fixed logic issue, I'll work on the editing issue

**Comment by WastefulNick** [comment]
Both issues fixed. Closed.
